# Generated by Django 4.2.25 on 2025-10-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('priority', models.IntegerField(default=3, help_text='Priority from 1 (High) to 5 (Low)')),
            ],
        ),
    ]
